### PR TITLE
Infection mechanics

### PR DESCRIPTION
**Pull request by Profugo-Barbatus**
Pushing Infection Mechanics to Master branch in anticipation of release 1.0

### CODE REVIEW

**Review by RealTelefonmast — CHANGES_REQUESTED** [review]
Results of play test:
New protection codes work for the suit, but starts bugging out on pawns and animals. Multiple infections are created on prolonged contact to Tiberium i.e walking through large amounts of Tiberium.

Bug should be fixed asap at best

**Comment by Profugo-Barbatus** [comment]
Updates pushed. Should restore original, single-infection behavior.

**Comment by Profugo-Barbatus** [comment]
Suit Hotfix pushed. Please review changes.

**Review by RealTelefonmast — APPROVED** [review]
Tested in game;
Suits protect fully, no more multiple infections

**Pull request merged**
